const MULTIPLICATION: string = "MULTIPLICATION_OPERATOR";
const DIVISION: string = "DIVISION_OPERATOR";
const ADDITION: string = "ADDITION_OPERATOR";
const SUBTRACTION: string = "SUBTRACTION_OPERATOR";

export { MULTIPLICATION, DIVISION, ADDITION, SUBTRACTION };
